# data
notes: "Increase hand mimic weight"

# training parameters
gamma: 0.95
tau: 0.95
policy_htype: gelu
policy_hsize: [2048, 1024, 512]
policy_optimizer: "Adam"
policy_lr: 5.e-5
policy_momentum: 0.0
policy_weightdecay: 0.0
value_htype: gelu
value_hsize: [2048, 1024, 512]
value_optimizer: "Adam"
value_lr: 3.e-4
value_momentum: 0.0
value_weightdecay: 0.0
clip_epsilon: 0.2
min_batch_size: 50000
mini_batch_size: 50000
num_optim_epoch: 5
log_std: -2.3
fix_std: true
num_epoch: 20000
seed: 1
save_n_epochs: 100
reward_id: "world_rfc_explicit"
obs_type: 4
actor_type: "gauss"
num_primitive: 8
action_v: 1
obs_v: 2
fut_frames: 3
skip: 10
reactive_v: 0
reactive_rate: 0.3
sampling_temp: 0.1
sampling_freq: 0.5

reward_type: 9
reward_weights:
  w_p: 0.25
  w_v: 0.1
  w_wp: 0.2
  w_j: 0.45
  w_op: 0.2
  w_or: 0.4
  w_ov: 0.1
  w_orfc: 0.1   # 0.3
  k_p: 1.0      # 2.0
  k_v: 0.05
  k_wp: 1.0   # 5.0
  k_j: 2.0   # 100.0
  k_op: 10.0
  k_or: 1.0
  k_ov: 0.05
  k_orfc: 0.1   # 1.0

data_specs:
  dataset_name: Tracking
  seq_name: dexycb_bottle_seq
  expert_fn: sample_data/Hotrack/bottle/dexycb_bottle_seq_train.pkl
  test_expert_fn: sample_data/Hotrack/bottle/dexycb_bottle_seq_test.pkl
  clip_s: 0     # for single clip only
  clip_e: 600   # for single clip only
  max_len: 200
  motion_freq: 30
  sample_freq: 1
  with_obj: true
  obj_fn: assets/Hotrack/mustard_bottle.xml
  cano_obj_fn: sample_data/SingleDepth/Cup/Seq1/obj_v.txt # for SingleDepth object only


# expert and environment
render: false
meta_pd: false
meta_pd_joint: false
mujoco_model: assets/hand_model/manohand_reduce2/mano_hand_tip
vis_model: assets/hand_model/manohand_reduce2_duo/mano_hand

sim_step: 15
future_w_size: 5
env_episode_len: 100000
env_term_body: "body"
env_expert_trail_steps: 0
obs_coord: "root"
obs_phase: false
random_start: false
pos_diff_thresh: 0.1
rot_diff_thresh: 1.0
jpos_diff_thresh: 0.1
obj_pos_diff_thresh: 0.1
obj_rot_diff_thresh: 1.0

# RFC parameters
residual_force: True
residual_force_scale: 20.0
residual_torque_scale: 1.0
residual_force_mode: explicit
rfc_decay: false
rfc_decay_max: 10000

# other joint and body parameters
joint_params:
  # ["name", "k_p", "k_d", "torque_limit"]
  - ["robot0:slide0", 50.0, 5.0, 50.0]
  - ["robot0:slide1", 50.0, 5.0, 50.0]
  - ["robot0:slide2", 50.0, 5.0, 50.0]
  - ["robot0:WRJ0", 5.0 , 0.5, 5.0]
  - ["robot0:WRJ1", 5.0 , 0.5, 5.0]
  - ["robot0:WRJ2", 5.0 , 0.5, 5.0]
  - ["robot0:FFJ3y", 1.0 , 0.1, 1.0]
  - ["robot0:FFJ3z", 1.0 , 0.1, 1.0]
  - ["robot0:FFJ2z", 1.0 , 0.1, 1.0]
  - ["robot0:FFJ1z", 1.0 , 0.1, 1.0]
  - ["robot0:MFJ3y", 1.0 , 0.1, 1.0]
  - ["robot0:MFJ3z", 1.0 , 0.1, 1.0]
  - ["robot0:MFJ2z", 1.0 , 0.1, 1.0]
  - ["robot0:MFJ1z", 1.0 , 0.1, 1.0]
  - ["robot0:LFJ3y", 1.0 , 0.1, 1.0]
  - ["robot0:LFJ3z", 1.0 , 0.1, 1.0]
  - ["robot0:LFJ2z", 1.0 , 0.1, 1.0]
  - ["robot0:LFJ1z", 1.0 , 0.1, 1.0]
  - ["robot0:RFJ3y", 1.0 , 0.1, 1.0]
  - ["robot0:RFJ3z", 1.0 , 0.1, 1.0]
  - ["robot0:RFJ2z", 1.0 , 0.1, 1.0]
  - ["robot0:RFJ1z", 1.0 , 0.1, 1.0]
  - ["robot0:THJ3x", 1.0 , 0.1, 1.0]
  - ["robot0:THJ3y", 1.0 , 0.1, 1.0]
  - ["robot0:THJ3z", 1.0 , 0.1, 1.0]
  - ["robot0:THJ2x", 1.0 , 0.1, 1.0]
  - ["robot0:THJ2y", 1.0 , 0.1, 1.0]
  - ["robot0:THJ2z", 1.0 , 0.1, 1.0]
  - ["robot0:THJ1y", 1.0 , 0.1, 1.0]
